server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: medimin-gateway

medimin:
  profile-service-url: ${PROFILE_SERVICE_URL:http://127.0.0.1:18081}
  care-service-url: ${CARE_SERVICE_URL:http://127.0.0.1:18082}

management:
  endpoints:
    web:
      exposure:
        include: health,info